### ISSUE TITLE
renderJTable should accept flat Json, not [Json]

### ISSUE THREAD

**Issue by brainrape** [slamdata/purescript-jtable#4]
According to the spec:
```
renderJTable :: TableStyle -> ColumnOrdering -> [Json] -> Markup
```
Why is it necessary to wrap a Json (that is possibly a JArray) with an array?
Having a single Json at hand (be it list or object) is a more likely scenario - think api response.

Note that JArray is a type synonym for [Json].

So:
```
renderJTable :: TableStyle -> ColumnOrdering -> Json -> Markup
```

**Comment by Fresheyeball** [comment]
Why does this matter? Json with a top level Array should render the same wrapped in a List. Its likely that consumers of this api may have multiple Json objects they wish to render as a collection. Changing the signature to from `[Json]` to `Json` would force consumers to go through an additional expensive transformation step parsing and then rejoining their Json objects into one with a top level Array.

**Comment by brainrape** [comment]
Not, it wouldn't. There's Data.Argonaut.Core.fromArray if you really need it. 
Not having the Json wrapped not only makes the api simpler, it's what you'd want in most use cases.

**Comment by jdegoes** [comment]
I have an expectation that each entry in the `[Json]` array will be mapped to a `tr` element. i.e. it's the structure of the array that gives you multiple top-level `tr` elements in the top-level `table` element. 

Without `[Json]`, there would be two ways of interpreting `[1, 2, 3]`: as a single row with 3 columns, or as 3 rows with one column. 

Whereas in the current spec, the array passed to the rendering function will have the same length as the number of `tr`'s (excluding the header) in the top-level `table`, so there is no ambiguity.
