### ISSUE TITLE
Remove JSemantic?

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-jtable#42]
There are a few dodgy things in here (`Currency` is a `Number`????? 😱). Do we want to just tear most of it out and show JSON primitives (like the pivot table does?).

https://github.com/slamdata/purescript-jtable/blob/master/src/Data/Json/JSemantic.purs#L58-L74

/cc @jdegoes @garyb @cryogenian

**Comment by garyb** [comment]
:bomb: :100:
