### ISSUE TITLE
Specify Level in TableStyle

### ISSUE THREAD

**Issue by brainrape** [slamdata/purescript-jtable#5]
```
data TableStyle = 
  TableStyle { 
    table   :: Level -> -- is this a top-level table? or a nested table?
               Markup -> Markup,
    cell    :: JSemantic -> Markup -> Markup, 
    head    :: JPath -> Markup -> Markup,
    row     :: Markup -> Markup }
```
(comment from the readme)

What determines the nesting level of a table? The number of nested arrays?
Besides, it is more reasonable to use only one `<table>` (with row/col spans) since styling is easier and automatic alignment works. It's also faster to render.

**Comment by jdegoes** [comment]
Using nested tables would be the only way to accommodate heterogeneous data, e.g. tuples of differing lengths appearing in different rows. It's possible a user may want to style these differently so the level is exposed to the styler.

**Comment by brainrape** [comment]
The columns of nested tables wouldn't align between different tables nested at the same depth, with the same number of columns (if the widhs aren't fixed). Isn't that a problem?
With variable length tuples, i'd prefer padding with empty cells until the maximum tuple length - after all, these are "missing values". The other solution, to split the cell into varying numbers of sub-cells, is not very appealing.

**Comment by jdegoes** [comment]
Good point. If I can't think of any other use cases for nested tables, I'll delete it from the spec. My concern was just giving all nesting information to the styler so it doesn't have to introspect on the element it's styling.
